/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0FCcVhPbS9KZ3VVaUxTRzN0WmpUTVd4bHlBMlh3RkxzQURlS2RIcVRXOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSjQ2Z3JYZjh3YVNnZ3QvTStxSzNQN1kvOTBacVY0SmRrTEZXM3dWdnJsQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4R21vSzdZTFVNWlpVbThvYkgvMzFuSHg5bVFERThaenpNZ1NCR0hRU1hzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTUlRYZlQzVlRiSG5RdmhrV2M3V3U5bW1WaTNWZ05ZNjUzOFYxaFRzMWk4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFCaVpZd2tPSnJweG1uQlNmTnBEM0VrT05tZnlNSnQyVkJoNWs0R3VOMVU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndkaDY2MEF0TlY5REtoK1NyeThHU2lHUVo4TUFha2l4YngzNFl2L3RiQnM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR05USkVIdE5xUW8zWjBnQzZVT3hpY3d5NnZ0QUpoZlU2M2liOUZCamptZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieitZUzJ0emtxLzc5ZXZKKzByY2EwOG5XaTBneUZsN0xPZVllaGFTd21TYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpyRmtzWmFlMEp4R1ZjdEhHQlpFd2R0YkNobVFyOHRoNXYzOUMrUExodERzV1VmUVF0OEVJU2lRY25ONmU3VlRKK09nMHJMVEsrVFRDUXAwUVMrSmpRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjExLCJhZHZTZWNyZXRLZXkiOiJ1WnNtMkRHYW52djl2T2tkb3hDK1RYWU1RMFJqSjZjWHk5ME84SWtPVXBNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc2OTM2NTYxN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI2RjhGNzE5NDY5QjJBQzcxOTc2RjQ4OUM2RjE5N0M0QiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI4NTkyNjQ2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NjkzNjU2MTdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOThEODBDMDUxOEY0MTQzQTg1ODlFNTJFOTA2M0NDRTQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODU5MjY1Mn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzY5MzY1NjE3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6Ijg2NkNEODcwNjRFNzc5MUI4QjhDQ0QxRjJCQTIwMUUyIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3Mjg1OTI2Njl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc2OTM2NTYxN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzMjUxRTFCNkIyRjQ3MTE4Mzk5ODdCMzY5MkQ4NTNFQyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI4NTkyNjgyfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJVczg0OHo0WlJoT0wzUGg5TDJLSDdBIiwicGhvbmVJZCI6ImUzNjVjMjVhLTQ5MjktNDIwMS1hYWUyLTI2MGQyNTkwNWUyNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNcUJXUXBEdFdkM1FnZ3hhOTVBbXcxU2hkeFU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid3lHcmlyalVqU1V3U3NZL21Wb1lLN2RIcHc4PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjgxTTY0MURQIiwibWUiOnsiaWQiOiIyNTQ3NjkzNjU2MTc6MTdAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSsWC4oKm4oKpxYLFguKxoCDwn5W377iPIMOY4oKm4oKyxYLigqZKw5jwn5W477iPIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKYmYvSjBCRU83MW9MZ0dHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI5czg3aEZBRm5oS1ZsUGxLa0wycjlSODZuZVFwLzFFNkV4VkdlSkN3Mm13PSIsImFjY291bnRTaWduYXR1cmUiOiJHSlJZQjJkM3BxY1FnMGtyTVdJVVhFc3VSZGxhUlVHb3BFaHBRZFhMZzk4Zlp2K2k1a0hXL1E1dVhBR3UvQVhhWkcxUmI3dDlxYWZWdjFPY1c2QXdCQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoidjNyL2pRM2g2U3lKZisxM2U1N1crR2RGdHFLSzNMMEhnK2h0R3BPR21qSTJnRUlVKyt6dVl0aVV6V1BRWWVRcGl3K2s1cy9oZDlMU1NMVVRJVnNoaHc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NjkzNjU2MTc6MTdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZmJQTzRSUUJaNFNsWlQ1U3BDOXEvVWZPcDNrS2Y5Uk9oTVZSbmlRc05wcyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyODU5MjYzNSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFQMjEifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Jinwiil';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254769365617';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
