/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEhXSjFqemVlU3NWR2dXbU1vRGlTUmIzY1lQNDQ5TTd6b0FsYVNCOXFtZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia3dLancwc1hWQ0JKelZkdlptT0dwOVhZRGJoa2g1bVdySUFrY2FDVEVYWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJS3RXN2g2WHZ4d2JpN3d4TmR0MmdzS3M4ZzNlY2NVUFlvdExrUXpyZzFBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJWTnBNVjRObytxOElJdEs2cS8ybTBNa2J6MnpzY0dqYzFHZE50NUF3THlVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklCZitHbW9FWXJscUVweEI2bWNDTlZOLzgrZlpIT0pQRTJTN0s5WDRqa2s9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InA2UmhhdEFoQ3dwSm5sWnlJYlpxRWQ4Y01mT2c4di9vYk5jRGRXbE9zQUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUx4bmtTUENtUDV3bXFRRjUyZlZRMWQ3b0tBRGExaXRwSkc4cHV2eVZXZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTzRxR3hScWVBR1QrV3c4NmlESElmcVF6bnBPVkUzNmhzN0d1b1lLQUV5dz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklpQi9LUVFHaXNGKzc2c0k0ZitWbUg3dkdETm9XREwvTTFmblludnVqY0hWQmkwRDAvbDlrRlN4VXMvblJ5V04vdjhqbVNWMDVoTEpNUUxUUWRveWlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA4LCJhZHZTZWNyZXRLZXkiOiJlSWFqM2ZORk1EelpaTU9oUTFLQ1NZcVRZUWNiQVJ0ZXRkUkFPdk1GMGNZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc4NDMyMDk1OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1NERCNTQ2MzJGNkY4RUI4QTE2N0MzQkIyNjE4NDc5RiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMxMDU2MDE3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3ODQzMjA5NThAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRENBQzJDMUNGMjZEM0Q0MEQ3NzZGNTFFMEYxNERDMDEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMTA1NjAyM31dLCJuZXh0UHJlS2V5SWQiOjM1LCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzUsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiLVVQQ2ZpWVJRWGUzMU4wazZ3UVJFQSIsInBob25lSWQiOiIyODljODQyMi00OTNmLTQ1NDctYjI0YS03YjJiMjJkNWUzMmYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVkVIM29oOThNQkhMNnVaOXRPbXVLWDJSQXZvPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhPc3plcWVaTXB1WmQyZEt4U09EWnNMTUg0Yz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI2R0RDMUc2RSIsIm1lIjp7ImlkIjoiMjU0Nzg0MzIwOTU4Ojg5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkZpbmpvaG5zIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKaU9sUHNGRU9paXQ3a0dHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJIeHljTVRjZnhGTk9ibUgwVjZGN2Q0R3VLQWg1QlByYUt1Nnd4WUFYSFZrPSIsImFjY291bnRTaWduYXR1cmUiOiI4Rkl2b2pwdXU1dmFMRmhyOWFVUHY5QWNxZUtUNTNPVEQ5bjVNQStMZE5rMnFDc3ZxcXJOR3ZlOWFYRERZV2xyYURwelMxUFZrNURmL2tyM3ZjV0dDdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiVFplS2ZCY01kUWpPaHBKOGRKNVgvbDVVeFBrNkZGWnMvWWphQjNaZWVIQUt4RDd0VmtucTZLbjJmUk5pWklINnJEMjFMTGJxOW4zR09TWG5qcy9EaEE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3ODQzMjA5NTg6ODlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUjhjbkRFM0g4UlRUbTVoOUZlaGUzZUJyaWdJZVFUNjJpcnVzTVdBRngxWiJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMTA1NTk5MCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBaUMifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254784320958';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
